### ISSUE TITLE
angular-cypress: No ct option generated for project

### ISSUE THREAD

**Issue by Timeout-Timo** [jscutlery/devkit#105]
After support for standalone projects was added, the documentation changed a bit.
Furthermore, the component starter should be managed over Angular-Context (which is a good idea, especially when implementing #97). But in the setup-part, the ct-option is not added to angular.json.

After executing ```ng run my-project:ct ``` this happened:  An unhandled exception occurred: Project target does not exist.
```
[error] Error: Project target does not exist.
    at findProjectTarget (~/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:29:15)
    at Object.getBuilderName (~/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:42:46)
    at WorkspaceNodeModulesArchitectHost.getBuilderNameForTarget (~/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:80:35)
    at RunCommand.runSingleTarget (~/node_modules/@angular/cli/models/architect-command.js:161:55)
    at RunCommand.runArchitectTarget (~/node_modules/@angular/cli/models/architect-command.js:201:35)
    at RunCommand.run (~/node_modules/@angular/cli/commands/run-impl.js:15:25)
    at RunCommand.validateAndRun (~/juniorjob-webapp/node_modules/@angular/cli/models/command.js:136:33)
    at async Object.runCommand (~/node_modules/@angular/cli/models/command-runner.js:205:24)
    at async default_1 (~/node_modules/@angular/cli/lib/cli/index.js:70:31)
```

**Comment by Timeout-Timo** [comment]
Old Version. Is fixed in version 0.8.0

CLOSED
